version: '2'

services:

  redis:
    image: redis:3.0
    environment:
     - "SERVICE_NAME=redis"

  nodeapp:
    image: bargenson/dockerdemo_nodeapp
    build: ./app
    environment:
     - "REDIS_HOST=redis"
     - "PORT=8080"
     - "DEBUG=true"
     - "SERVICE_NAME=nodeapp"
    ports:
     - "8080"

  web:
    image: bargenson/dockerdemo_web
    build: ./nginx
    ports:
     - "80:80"
    environment:
     - "SERVICE_IGNORE=true"
     - "CONSUL_HOST=${CONSUL_HOST}"
     - "CONSUL_PORT=${CONSUL_PORT}"