redis:
  image: redis:3.0
  environment:
   - "SERVICE_NAME=redis"

nodeapp:
  image: bargenson/dockerdemo_nodeapp
  environment:
   - "REDIS_HOST=dockerdemo_redis_1"
   - "PORT=8080"
   - "DEBUG=true"
   - "SERVICE_NAME=nodeapp"
  ports:
   - "8080"

#nodeapp2:
#  image: bargenson/dockerdemo_nodeapp
#  environment:
#   - "REDIS_HOST=dockerdemo_redis_1"
#   - "PORT=8080"
#   - "DEBUG=true"
#   - "SERVICE_NAME=nodeapp"
#   - "affinity:container!=~dockerdemo_nodeapp*"
#  ports:
#   - "8080"

web:
  image: bargenson/dockerdemo_web
  ports:
   - "80:80"
  environment:
   - "SERVICE_IGNORE=true"
   - "CONSUL_HOST=${CONSUL_HOST}"
   - "CONSUL_PORT=8500"
